#!/bin/sh

# This script is designed to help you clean your computer from unneeded
# packages. The script will find all packages that no other installed package
# depends on. It will output this list of packages excluding any you have
# placed in the ignore list. You may browse through the script's output and
# remove any packages you do not need.#

# Original Idea: https://wiki.archlinux.org/index.php/Pacman/Tips_and_tricks#Not_in_a_specified_group_or_repository
# Depends on pacman, sort, tr and uniq
#
# Author: Till Mahlburg
# License: CC0

# SETTINGS #
# groups to not include in list
ignored_groups="base base-devel"
# packages to not include in list. Must be installed or else they will show
# up in the list.
ignored_packages=""

# LOGIC #
# create list of ignored packages. Not quoted deliberatly.
ignored_groups=$(pacman -Sqg $ignored_groups)
for package in $ignored_packages; do
    temp_package_list="$package\n$temp_package_list"
done
# concatenate both list and remove duplicates
ignored_packages=$(printf "%s\n%s" "$temp_package_list" "$ignored_groups" | sort | uniq)

# list all explicitly installed files
explicitly_installed=$(pacman -Qqt)

# compare both lists and create a difference. set operation as explained here:
# http://blog.deadvax.net/2018/05/29/shell-magic-set-operations-with-uniq/
# and then trimmed to shape.
printf "%s\n%s\n%s" "$explicitly_installed" "$explicitly_installed" "$ignored_packages" | sort | uniq -c | grep "2 " | tr -s ' ' | cut -f 3 -d ' '
