#! /bin/sh

##  @@@  @@@  @@@   @@@@@@    @@@@@@@   @@@@@@   @@@@@@@@@@   ##
##  @@@  @@@  @@@  @@@@@@@@  @@@@@@@@  @@@@@@@@  @@@@@@@@@@@  ##
##  @@!  @@!  @@!  @@!  @@@  !@@       @@!  @@@  @@! @@! @@!  ##
##  !@!  !@!  !@!  !@!  @!@  !@!       !@!  @!@  !@! !@! !@!  ##
##  @!!  !!@  @!@  @!@!@!@!  !@!       @!@  !@!  @!! !!@ @!@  ##
##  !@!  !!!  !@!  !!!@!!!!  !!!       !@!  !!!  !@!   ! !@!  ##
##  !!:  !!:  !!:  !!:  !!!  :!!       !!:  !!!  !!:     !!:  ##
##  :!:  :!:  :!:  :!:  !:!  :!:       :!:  !:!  :!:     :!:  ##
##   :::: :: :::   ::   :::   ::: :::  ::::: ::  :::     ::   ##
##    :: :  : :     :   : :   :: :: :   : :  :    :      :    ##

# A script to set the preferred options for my wacom intuos draw
# License: CC0

xsetwacom set "Wacom Intuos S 2 Pen stylus" Button 2 "button +2";
xsetwacom set "Wacom Intuos S 2 Pen stylus" Button 3 "button +3";
xsetwacom set "Wacom Intuos S 2 Pen stylus" Button 1 "button +1";
xsetwacom set "Wacom Intuos S 2 Pad pad" Button 3 "key +ctrl + -ctrl";
xsetwacom set "Wacom Intuos S 2 Pad pad" Button 9 "key +ctrl z -ctrl";
xsetwacom set "Wacom Intuos S 2 Pad pad" Button 2 "key +ctrl - -ctrl";
xsetwacom set "Wacom Intuos S 2 Pad pad" Button 8 "key +ctrl y -ctrl";
